/**
 * Icon re-exports from lucide-react for design-system consistency.
 * Consumers import {Heart, Plus, ...} from '@regenai/ui' rather than
 * directly from lucide-react so we can swap icon sets project-wide later.
 */

export {
  Heart,
  Plus,
  Minus,
  X,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowLeft,
  Search,
  ShoppingCart,
  User,
  Menu,
  Info,
  AlertTriangle,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Loader2,
  Star,
  Trash2,
  Settings,
  LogOut,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Calendar,
  Clock,
  ExternalLink,
  Download,
  Upload,
  Copy,
  Share2,
  Filter,
  SlidersHorizontal,
  Globe,
  Languages,
  Sun,
  Moon,
  Sparkles,
  Zap,
  Shield,
  ShieldCheck,
  Award,
  Activity,
  HeartPulse,
  BookOpen,
  MessageCircle,
  Mail,
} from 'lucide-react';

export type {LucideIcon} from 'lucide-react';
