/// <reference types="@cloudflare/workers-types" />

import {createRequestHandler} from 'react-router';

/**
 * Cloudflare Workers module entry for @regenai/app.
 *
 * Day 15 scaffold — hands off every request to React Router's built-in
 * handler. OAuth install + HMAC verification land in D15.3; those
 * routes live under `/auth/*` inside the Router.
 */

// eslint-disable-next-line import/no-unresolved -- virtual module generated by @react-router/cloudflare
import * as build from 'virtual:react-router/server-build';

const handler = createRequestHandler(build);

export default {
  async fetch(request: Request, env: Env, executionCtx: ExecutionContext): Promise<Response> {
    try {
      return await handler(request, {env, executionCtx});
    } catch (err) {
      console.error('[regenai-app] unhandled', err);
      return new Response('Internal server error', {status: 500});
    }
  },
} satisfies ExportedHandler<Env>;
